version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: reachinbox_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: reachinbox_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: reachinbox_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: reachinbox_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"